"""initial_schema

Revision ID: 256feba30316
Revises: 
Create Date: 2026-06-02 19:44:18.372629

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '256feba30316'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('success_cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('requirement_hash', sa.String(length=64), nullable=False),
    sa.Column('requirement_preview', sa.String(length=200), nullable=False),
    sa.Column('full_requirement', sa.Text(), nullable=False),
    sa.Column('plan_json', sa.Text(), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=False),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('module_count', sa.Integer(), nullable=True),
    sa.Column('passed_count', sa.Integer(), nullable=True),
    sa.Column('blocked_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_success_cases_requirement_hash'), 'success_cases', ['requirement_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_success_cases_requirement_hash'), table_name='success_cases')
    op.drop_table('success_cases')
    # ### end Alembic commands ###
